easy_admin:
    user:
        display_name: true
        display_avatar: true
        avatar_property_path: 'gravatar'
    site_name: '<img src="/images/logo.png" style="height: 10vh;"  alt="">'

    design:
        menu:
            - { entity: 'Projects', label: 'Projects', icon: 'project-diagram' }
            - { entity: 'Pofile', label: 'Components', icon: 'prescription-bottle' }
            - { entity: 'Releases', label: 'Releases', icon: 'save' }
            - { entity: 'User', label: 'Users', icon: 'user' }
        brand_color: '#a41eb0'

    entities:
        Pofile:
            class: App\Entity\PoFile
            controller: App\Controller\PofileController
            disabled_actions: ['show', 'edit']
            form:
                fields:
                    - 'Project'

        User:
            class: App\Entity\User

        Projects:
            class: App\Entity\Projects
            form:
                fields:
                    - { property: 'Name', label: 'Name' }
                    - { property: 'Description', label: 'Description' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'repository', type: 'text', label: 'Repository' }
                    - { property: 'Branch', label: 'Branch' }
                    - { property: 'Users', label: 'Users' }
            list:
                fields:
                    - { property: 'Name', label: 'Name' }
                    - { property: 'Description', label: 'Description' }
                    - { property: 'Icon', type: 'image', base_path: '%gameIcon%' }
                    - { property: 'Users', label: 'Nº Users' }
                    - { property: 'poFiles', label: 'Nº Components' }
                    - { property: 'releases', label: 'Nº Releases' }

        Releases:
            class: App\Entity\Releases
            form:
                fields:
                    - { property: 'Version', label: 'Version' }
                    - { property: 'Changelog', label: 'Changelog' }
                    - { property: 'downloadFile', type: 'vich_file' }
                    - { property: 'Md5', type: 'text', label: 'MD5' }
                    - { property: 'Project', label: 'Project' }
            list:
                fields:
                    - { property: 'Version', label: 'Version' }
                    - { property: 'Project', label: 'Project' }
                    #- { property: 'downloadFile', template: 'Releases/download.html.twig', base_path: '%gameReleases%' }