vich_uploader:
    db_driver: orm

    mappings:
        Projects:
            uri_prefix: '%gameIcon%'
            upload_destination: '%kernel.project_dir%/public/%gameIcon%'
        Releases:
            uri_prefix: '%gameReleases%'
            upload_destination: '%kernel.project_dir%/public/%gameReleases%'
